FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

# install python + build deps
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    gcc \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# create venv (fixes PEP 668 issue)
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Java already included in base image
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH=$JAVA_HOME/bin:$PATH

COPY docker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app